### ISSUE TITLE
Is this typo?

### ISSUE THREAD

**Issue by COx2** [hotwatermorning/Terra#21]
About the sentence of "Vst::BusDirection", it seems more better to "Vst::BusDirections".

https://github.com/hotwatermorning/Terra/blob/003d92cbc47323d24e6f687775187be56c19ea4a/Terra/plugin/vst3/Vst3PluginImpl.hpp#L81

**Comment by hotwatermorning** [comment]
Thank you for your suggestion. @COx2 

um... let me explain details of this issue.

The vst3sdk defines enumerator types as plural form names, and defines alias names as singular form names corresponding to the enumerator types for integer types which are used to representing the enumerator values

In Terra's code, I have not paid attention so much to difference of these names because:

* Mixed use of these name did not cause of important problems.
* If using only enumerator types (i.e. plural form names) instead of alias names, additional cast operation was required to exchange values from/to vst3sdk in some cases.

However, mixed use of these names can cause confusion, and now I think that it may be more better for the code consistency to using only enumerator types.

I'll fix it later.

**Comment by COx2** [comment]
Thank you for the details.
Since I don' t familiar to the VST-MA's coding standard, your explanation helped me to understand the intent of the code.

**Comment by hotwatermorning** [comment]
fixed in 9464ec3
